// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fiftyhrtz.phone.domain;

import com.fiftyhrtz.phone.domain.PhoneGallary;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PhoneGallary_Roo_Configurable {
    
    declare @type: PhoneGallary: @Configurable;
    
}
