// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fiftyhrtz.phone.domain;

import com.fiftyhrtz.phone.domain.LogUserRole;
import com.fiftyhrtz.phone.domain.LogUserRoleDataOnDemand;
import com.fiftyhrtz.phone.domain.LogUserRoleIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LogUserRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LogUserRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LogUserRoleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LogUserRoleIntegrationTest: @Transactional;
    
    @Autowired
    LogUserRoleDataOnDemand LogUserRoleIntegrationTest.dod;
    
    @Test
    public void LogUserRoleIntegrationTest.testCountLogUserRoles() {
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to initialize correctly", dod.getRandomLogUserRole());
        long count = LogUserRole.countLogUserRoles();
        Assert.assertTrue("Counter for 'LogUserRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LogUserRoleIntegrationTest.testFindLogUserRole() {
        LogUserRole obj = dod.getRandomLogUserRole();
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to provide an identifier", id);
        obj = LogUserRole.findLogUserRole(id);
        Assert.assertNotNull("Find method for 'LogUserRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LogUserRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LogUserRoleIntegrationTest.testFindAllLogUserRoles() {
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to initialize correctly", dod.getRandomLogUserRole());
        long count = LogUserRole.countLogUserRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'LogUserRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LogUserRole> result = LogUserRole.findAllLogUserRoles();
        Assert.assertNotNull("Find all method for 'LogUserRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LogUserRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LogUserRoleIntegrationTest.testFindLogUserRoleEntries() {
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to initialize correctly", dod.getRandomLogUserRole());
        long count = LogUserRole.countLogUserRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LogUserRole> result = LogUserRole.findLogUserRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LogUserRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LogUserRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LogUserRoleIntegrationTest.testFlush() {
        LogUserRole obj = dod.getRandomLogUserRole();
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to provide an identifier", id);
        obj = LogUserRole.findLogUserRole(id);
        Assert.assertNotNull("Find method for 'LogUserRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLogUserRole(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'LogUserRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LogUserRoleIntegrationTest.testMergeUpdate() {
        LogUserRole obj = dod.getRandomLogUserRole();
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to provide an identifier", id);
        obj = LogUserRole.findLogUserRole(id);
        boolean modified =  dod.modifyLogUserRole(obj);
        Integer currentVersion = obj.getVersion();
        LogUserRole merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'LogUserRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LogUserRoleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to initialize correctly", dod.getRandomLogUserRole());
        LogUserRole obj = dod.getNewTransientLogUserRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LogUserRole' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'LogUserRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LogUserRoleIntegrationTest.testRemove() {
        LogUserRole obj = dod.getRandomLogUserRole();
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LogUserRole' failed to provide an identifier", id);
        obj = LogUserRole.findLogUserRole(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LogUserRole' with identifier '" + id + "'", LogUserRole.findLogUserRole(id));
    }
    
}
